# ============================
# Project-wide Gradle settings
# ============================

# JVM memory for Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Performance optimizations
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# ============================
# AndroidX (OBLIGATORIO)
# ============================
android.useAndroidX=true
android.enableJetifier=true

# ============================
# compileSdk 35 (AGP 8.5.2)
# ============================
android.suppressUnsupportedCompileSdk=35

# ============================
# Kotlin
# ============================
kotlin.code.style=official

# ============================
# Compose
# ============================
android.compose.compiler.report=false
android.compose.compiler.metrics=false

# ============================
# Versioning
# ============================
APP_VERSION_NAME=1.0.0
APP_VERSION_CODE=1

# ============================
# Deprecated flags (mantener en false)
# ============================
android.builtInKotlin=false
android.newDsl=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
